name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t fraud-detection-model .
        docker tag fraud-detection-model:latest ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model:latest
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "fraud-detection-model"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
